### ISSUE TITLE
the Treccani list no longer appears in the search bar

### ISSUE THREAD

**Issue by CaneRandagio1983** [giuse94/TreccaniSearch#9]
When I installed the extension it worked very well, now it hasn't worked as before for a few months.

In essence, when typing the word, the Treccani list of synonyms, dictionary, etc. no longer appears.... only an element appears which refers to a Treccani page where you can choose whether you want to view the vocabulary, the synonyms or the encyclopedia of that word

**Comment by giuse94** [comment]
Thank you for reporting this issue, it will be fixed in the next release (I can't say right now when it will be published).

**Comment by giuse94** [comment]
@CaneRandagio1983 Fixing the problem was easy, but it looks like I'm locked out of my Mozilla account and can't upload the new version. I'll try to work around the problem. Sorry for the inconvenience.

**Comment by CaneRandagio1983** [comment]
well let's hope you can solve it quickly! good luck and thank you

**Comment by CaneRandagio1983** [comment]
Hi! Do you have some news about the bug correction?

Il giorno dom 10 mar 2024 alle ore 10:29 giuse94 ***@***.***>
ha scritto:

**Comment by giuse94** [comment]
Unfortunately, I can no longer sign in my own Mozilla account to publish the new version of the extension. The only workaround is to create a new account and publish a whole new extension, but I'm not in the mood for it. I'm afraid you won't be able to use the extension anymore. Sorry about that and thank you for giving it a try.

**Comment by CaneRandagio1983** [comment]
How sad! This extension was one of my favorites. Good luck!

Il giorno lun 27 mag 2024 alle ore 19:49 giuse94 ***@***.***>
ha scritto:

**Comment by CaneRandagio1983** [comment]
>
> Ciao! Message ID: ***@***.***> Sto
> decidendo se creare un'altra estensione per firefox sull' enciclopedia
> treccani.
>
Ma non riesco a trovare le API di treccani per accedere al vocabolario,
come hai risolto tu?

**Comment by giuse94** [comment]
Che io sappia quelle API non sono pubblicamente documentate, quindi ho dovuto usare gli strumenti per sviluppatori integrati nel browser per ispezionare le richieste e le risposte ottenute quando si cerca una parola sul sito della Treccani. In questo modo ho raccolto le informazioni che mi servivano.
